import React from 'react'

import Pixel from './Pixel'

// Generate a sequence of numbers
// Since the array is initialized with `undefined` on each position,
// the value of `v` below will be `undefined`
// Array.from({length: 5}, (v, i) => i);
// [0, 1, 2, 3, 4]

class App extends React.Component {
  render() {
    return (
      Array.from({length: 5000}, (v, i) => <Pixel />)
    )
    // return [
    //   <>
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //     <Pixel />
    //   </>
    // ]
  }
}

export default App
